name: Build & deploy

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          yarn global add @quasar/cli
          yarn install
      - name: Build Quasar SPA
        run: quasar build
      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: dist/spa

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: build
      - name: Upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "build/*"
          target: "~/test"
